"""add user_id to generations

Revision ID: ce70c5096fd0
Revises: b7da153e751a
Create Date: 2026-06-16 06:05:52.636654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce70c5096fd0'
down_revision: Union[str, None] = 'b7da153e751a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generations', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_generations_user_id'), 'generations', ['user_id'], unique=False)
    op.create_foreign_key(None, 'generations', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'generations', type_='foreignkey')
    op.drop_index(op.f('ix_generations_user_id'), table_name='generations')
    op.drop_column('generations', 'user_id')
    # ### end Alembic commands ###
